<?php include ('partials/header.phtml') ?>

<div class="container mx-auto max-w-2xl mt-10 mx-auto">
<div class="flex items-center justify-center ">
    <div class="self-center">
          <div class = "text-pink-500 pb-10 pl-20"> ADD A NEW TASK </div>
          <form method="POST" action="">
          <div class="pb-5">
               <label for="name" > Name</label>
               <input class="pl-5 border-2 border-pink-500" type="text" name="name" value="">
          </div>
       
          <div class="pb-5">
               <label for="author" > Author</label>
               <input class="pl-5 border-2 border-pink-500" type="text" name="author" value="" >
          </div>
          </form>
     </div>
     <div></div>
</div>
<?php include ('partials/footer.phtml') ?>