<?php include('partials/header.phtml') ?>

<!--------------------------------------->
<!-- Body -->
<!-- <body class="pt-24 sm:pt-20 lg:pt-165 justify-end"> -->


<div class="body-container mt-8 flex-grow bg-gray-200 p-2 mb-1 max-h-xs justify-center">
     <div class="flex items-center justify-center">
          <div class="w-full max-w-lg p-5 overflow-x-auto rounded-lg  shadow-xl rounded-lg shadow-xl max-w-auto shadow-pink-700 bg-gradient-to-br from-rose-100 via-rose-200 to-purple-300 bg-white ">

               <div class="flex justify-center items-center">
                    <h1 class="font-semibold tracking-light text-2xl text-4xl text-center mb-8 min-w-screen">Add new task!</h1>
               </div>
               <form method="POST" action="">
                    <div class="flex">   
                    <label class="my-1 py-1  h-8 w-1/4" for="name" >Task Name</label>
                    <input  class="my-1  h-8   w-2/3 rounded-lg" type="text"  name="name" required>
                    </div>


                    <div class="flex">
                         <label class="my-1 py-1 h-8 pr-2 w-1/4" for="author">Author</label>
                         <input class="my-1  h-8 pp-2 w-2/3 rounded-lg " type="text"  name="author" required>
                    </div>
                    <br>
                    <div class="pb-5 flex justify-center items-center">
                         <button class=" pb-2 bg-pink-500 hover:bg-pink-100 text-white hover:text-pink-700 font-bold py-2 px-4 rounded-full"
                              type="submit">Create task</button>
                         </br>
                    </div>
               </form>
               </div>
     </div>
</div>

<!--------------------------------------->

<!-- Your footer content here -->
<?php include('partials/footer.phtml') ?>
