<?php include('partials/headerHome.phtml') ?>

<!DOCTYPE html>
<html lang="en">

<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <script src="https://cdn.tailwindcss.com"></script>
     <title>Document</title>
</head>

<body class="">

<div
  id="carouselExampleSlidesOnly"
  class="relative table-container"

  data-te-carousel-init
  data-te-carousel-slide>
  <!--Carousel items-->
  <div class="relative w-full overflow-hidden after:clear-both after:block after:content-['']">
    <!--First item-->
    <div
      class="relative float-left -mr-[100%] w-full overflow-hidden transition-transform duration-[300ms] ease-in-out motion-reduce:transition-none"
      data-te-carousel-item
      data-te-carousel-active>
      <img
        src="<?php echo WEB_ROOT . "" ?>" class="block w-full" style="top:75px;" alt="Wild Landscape" />
    </div>
    <!--Second item-->
    <div class="relative float-left -mr-[100%] hidden w-full transition-transform duration-[300ms] ease-in-out motion-reduce:transition-none"
        data-te-carousel-item>
        <img src="<?php echo WEB_ROOT . "" ?>" class="block w-full" alt="Camera" />
    </div>
    <!--Third item-->
    <div class="relative float-left -mr-[100%] hidden w-full transition-transform duration-[300ms] ease-in-out motion-reduce:transition-none"
        data-te-carousel-item>
        <img src="<?php echo WEB_ROOT . "" ?>" class="block w-full" alt="Exotic Fruits" />
    </div>
 </div>
</div>
</body>

</html>
<?php include('partials/footer.phtml') ?>