<?php include('partials/headerHome.phtml') ?>

<!--------------------------------------->
<!-- Body : add class=" body-container" -->


<div
  id="carouselExampleSlidesOnly"
  class=" table-container body-container overflow-y-auto flex-grow mt-2 bg-gray-200 "
  data-te-carousel-init
  data-te-carousel-slide>
  <!--Carousel items-->

  <div class=" pl-2 pr-2 bg-gray-200 w-full overflow-hidden after:clear-both after:block after:content-['']">
    <!--First item-->
    <div
      class=" float-left -mr-[100%] w-full overflow-hidden transition-transform duration-[200ms] ease-in-out motion-reduce:transition-none"
      data-te-carousel-item
      data-te-carousel-active>
      <img
        src="<?php echo WEB_ROOT . "/images/fotosTeamDevelop/foto4.jpg" ?>" class="block w-full"  alt="Wild Landscape" />
    </div>
    <!--Second item-->
    <div class=" float-left -mr-[100%] hidden w-full transition-transform duration-[200ms] ease-in-out motion-reduce:transition-none"
        data-te-carousel-item>
        <img src="<?php echo WEB_ROOT . "/images/fotosTeamDevelop/foto2.jpg" ?>" class="block w-full" alt="Camera" />
    </div>
    <!--Third item-->
    <div class=" float-left -mr-[100%] hidden w-full transition-transform duration-[200ms] ease-in-out motion-reduce:transition-none"
        data-te-carousel-item>
        <img src="<?php echo WEB_ROOT . "/images//fotosTeamDevelop/foto8.jpg" ?>" class="block w-full" alt="Exotic Fruits" />
    </div>
    <!--Fourth item-->
    <div class=" float-left -mr-[100%] hidden w-full transition-transform duration-[200ms] ease-in-out motion-reduce:transition-none"
        data-te-carousel-item>
        <img src="<?php echo WEB_ROOT . "/images/fotosTeamDevelop/foto7.jpg" ?>" class="block w-full" alt="Exotic Fruits" />
    </div>
    <!--Fifth item-->
    <div class=" float-left -mr-[100%] hidden w-full transition-transform duration-[200ms] ease-in-out motion-reduce:transition-none"
        data-te-carousel-item>
        <img src="<?php echo WEB_ROOT . "/images/fotosTeamDevelop/foto5.jpg" ?>" class="block w-full" alt="Exotic Fruits" />
    </div>
    <!--Sixth item-->
    <div class=" float-left -mr-[100%] hidden w-full transition-transform duration-[200ms] ease-in-out motion-reduce:transition-none"
        data-te-carousel-item>
        <img src="<?php echo WEB_ROOT . "//images/fotosTeamDevelop/foto1.jpg" ?>" class="block w-full" alt="Exotic Fruits" />
    </div>
 </div>
</div>


<!--------------------------------------->
</div>
<!-- Your footer content here -->
<?php include('partials/footer.phtml') ?>
