<?php include ('partials/header.phtml') ?>

   

<div class="overflow-x-auto max-w-full "> 
 
     <div class="pl-20 pb-5 text-xl"> TASK VIEW</div>
     <table class="w-full text-md text-center text-gray-500 mb-6">
     <thead class="text-xs font-bold text-gray-700 uppercase bg-gray-900 md:bg-pink-700 sm:bg-blue-700">
        <tr> 
            <th class="p-2"> Task</th>
            <td class="p-2"><?php echo $this->task['name'];?> </td>
        </tr>
        <tr> 
            <th class="p-2"> Author</th>
            <td class="p-2"><?php echo $this->task['author'];?></td>
        </tr>
        <tr> 
            <th class="p-2"> Start</th>
            <td class="p-2"> <?php echo $this->task['start_time'];?></td>
        </tr>
        <tr> 
            <th class="p-2"> End </th>
            <td class="p-2"><?php echo $this->task['end_time'];?> </td>
        </tr>
        <tr> 
            <th class="p-2"> Status </th>
            <td class="p-2"><?php echo $this->task['status'];?> </td>
        </tr>
     </thead>>
     </table>

   </div>
   <div></div>
</div>   
<?php include ('partials/footer.phtml') ?>
