<?php include ('partials/header.phtml') ?>   
    <div class="grid grid-cols-3 gap-1">
      <div></div>
      <div>
        <table class = "text-sm table_auto">
            <thead>
                <tr>
                    <th class="pr-2 pb-5">Task</th>
                    <th class="pr-2 pb-5">Status</th>
                    <th class="pr-2 pb-5">Start-time</th>
                    <th class="pr-2 pb-5">End-time</th>
                    <th class="pr-2 pb-5">Author</th>
                    <th class="pr-2 pb-5">Actions</th>
                </tr>
            </thead>
        
            <tbody>
                <?php foreach($this->tasks as $task): ?>
                <tr>
                    <td class="pb-5 pr-3">  <?php echo $task['name']?> </td>
                    <td class="pb-5 pr-3"> <?php echo $task['status'] ?> </td>
                    <td class="pb-5 pr-3"> <?php echo $task['start_time'] ?> </td>
                    <td class="pb-5 pr-3"> <?php echo $task['end_time']?> </td>
                    <td class="pb-5 pr-3"> <?php echo $task['author'] ?> </td>
                    <td class="pb-5 pr-3"> 
                      <a href = "showTask?id=<?php echo $task['id']?>">View</a>  
                     <a href = "update?id=<?php echo $task['id']?>">Update </a>
                     <a href = "delete?id=<?php echo $task['id']?>"> Delete </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        </div>
        <div></div>
    </div> 
<?php include ('partials/footer.phtml') ?>
