<?php include(__DIR__ . '/partials/header.phtml'); ?>
<?php $task = $this->content; ?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>


    <title>TodoApp</title>
</head>

<body class="bg-grey-400"> <!-- bg-gradient-to-r from-blue-500 to-purple-500-->

  
<div class="overflow-x-auto mt-16">
        <table class="w-full text-sm text-left text-gray-500 mb-16 ">
       
        <thead class="text-xs text-gray-700 uppercase lg:shadow-pink-700 bg-pink-700 sm:bg-gray-700 md:bg-blue-700 lg:bg-pink-700 sticky top-0 ">
                <tr>
                    <th scope="col" class="px-6 py-3 text-left text-white">
                        Name
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-white">
                        Status
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-white">
                        Start time
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-white">
                        End time
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-white">
                        Author
                    </th>
                    <th scope="col" class="px-2 py-3 text-left text-white">

                    </th>
                    <th scope="col" class="px-2 py-3 text-left text-white">

                    </th>
                    <th scope="col" class="px-2 py-3 text-left text-white">

</th>
</tr>
</thead>
        
            <tbody>
            <?php foreach ($this->tasks as $task) : ?>
                    <tr class="bg-white border lg:border-pink-700 md:md:boder-blue-700 ">
                        <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap ">
                            <?php echo $task['name']; ?>
                        </td>
                        <td class="px-6 py-4 text-left">
                            <?php echo $task['status']; ?>
                        </td>
                        <td class="px-6 py-4 text-left">
                            <?php echo $task['start_time']; ?>
                        </td>
                        <td class="px-6 py-4 text-left">
                            <?php echo $task['end_time']; ?>
                        </td>
                        <td class=" py-4 text-left">
                            <?php echo $task['author']; ?>
                        </td>
                    <td class="pb-5 pr-3"> 
                      <a href = "showTask?id=<?php echo $task['id']?>">View</a>  
                     <a href = "update?id=<?php echo $task['id']?>">Update </a>
                     <a href = "delete?id=<?php echo $task['id']?>"> Delete </a>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        </div>
        <div></div>
    </div> 


</body>

</html>
<?php include ('partials/footer.phtml') ?>