</div>
</body>
<div class="footer">
<footer class="fixed bottom-0 left-0 w-full">
  <nav class="relative flex flex-wrap items-center justify-between px-2 py-3 bg-pink-700">
    <div class="container px-4 mx-auto flex flex-wrap items-center justify-between">
      <div class="font-serif text-xl w-full lg:w-auto px-4">
        &copy; Dream Developers Team, 2023
      </div>
    </div>
  </nav>
</footer>

</div>
</html>