</body>
<footer>
<nav class="relative flex flex-wrap items-center justify-between px-2 py-3 bg-pink-500 mb-3">
    <div class="container px-4 mx-auto flex flex-wrap items-center justify-between">
        <div class="font-serif text-xl w-full relative flex justify-between lg:w-auto  px-4 lg:static lg:block lg:justify-start">
            &copy; Team, 2023
        </div>
    </div>
</nav>
</footer>
</html>