<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
    <title>TODO</title>
</head>

<body>
    <div class="footer">
        <footer>
            <nav class="h-20 flex flex-wrap items-center py-2 bg-pink-700 sm:bg-gray-700 md:bg-blue-700 lg:bg-pink-700 m-1">
                <a class="font-serif text-xl w-full text-center text-white" href="<?php echo WEB_ROOT; ?>">
                    &copy; Dream Developers Team, 2023
                </a>
            </nav>
        </footer>
    </div>
</body>

</html>
