<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>ToDo App</title>
    <style>

    </style>
</head>
<div class="header">
    <header>
        <div class="w-full h-full flex justify-center mx-auto">
            <nav class="flex justify-between overflow-x-auto bg-pink-700 sm:bg-gray-700 md:bg-blue-700 lg:bg-pink-700 text-white w-full items-center">
                <div class="px-5 xl:px-8 py-4 flex flex-wrap w-full">
                    <a class="px-3 py-2 flex items-center uppercase font-sans text-xl text-black leading-snug hover:opacity-75" href=<?php echo WEB_ROOT; ?>>TO DO</a>

                    <div class="lg:flex flex-grow items-center">
                        <ul class="flex flex-wrap overflow-x-auto sm:text-center md:flex-nowrap lg:flex-wrap sm:flex-wrap xs:flex-col uppercase px-2 mx-auto font-semibold font-heading space-x-4 sm:space-x-6 md:space-x-10 lg:space-x-12 sm:items-center">
                            <li class="text-center mr-14">
                                <a class="sm:text-base hover:text-blue-200" href="create">Add New Task</a>
                            </li>
                            <li class="text-center">
                                <a class="hover:text-blue-200" href="showAll">Show all Tasks</a>
                            </li>
                        </ul>

                        <div class="ml-auto lg:ml-4">
                            <form id="myForm" method="POST" action="showAll" class="flex items-center">
                                <select name="db_type" data-te-select-init onchange="submitForm()" data-te-select-init class="block py-2 px-3 border border-gray-300 bg-pink-700 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500">
                                    <option value="json" <?php if ($_SESSION['db_type'] == 'json')
                                                                echo 'selected'; ?>>JSON</option>
                                    <option value="mysql" <?php if ($_SESSION['db_type'] == 'mysql')
                                                                echo 'selected'; ?>>MySQL</option>
                                    <option value="mongodb" <?php if ($_SESSION['db_type'] == 'mongodb')
                                                                echo 'selected'; ?>>MongoDB</option>
                                 
                                </select>
                                <label data-te-select-label-ref class="ml-2">Choose Database Type</label>
                            </form>
                        </div>

                    </div>
                </div>
            </nav>
        </div>
    </header>


    <body>