<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>
<header>
<div class="w-full h-full flex justify-center mx-auto">
<nav class="flex justify-between overflow-x-auto bg-pink-700 sm:bg-gray-700 md:bg-blue-700 lg:bg-pink-700 text-white w-full xs:p-4 items-center">
  <!-- Contenido del nav -->


    <div class="px-5 xl:px-12 py-6 flex w-full">
      <ul class="flex md:flex lg:flex sm:flex-row xs:flex-col uppercase px-2 mx-auto font-semibold font-heading space-x-4 sm:space-x-6 md:space-x-8 lg:space-x-12 items-center">
        <li class="text-center mr-14">
          <a class="flex hover:text-red-200" href="create">Add New Task</a>
        </li>
        <li class="text-center">
          <a class="hover:text-gray-200" href="show">Show all Tasks</a>
        </li>
      </ul>
    </div>
  </nav>
</div>
</header>
<body>