<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Document</title>
</head>

<body>
<header>
<div class=" flex justify-center  w-full h-full  mx-auto">
            <nav class="flex justify-between bg-pink-700 sm:bg-gray-700 md:bg-blue-700 lg:bg-pink-700 text-white w-full items-center">
                <div class="flex flex-wrap  sm:flex-col lg:px-6  xl:px-8 py-2  w-full">

                    <div class="lg:flex flex-grow items-center justify-center xl:mr-8 lg:pr-16 lg:mr-6 ">

                        <a href="<?php echo WEB_ROOT; ?>" class="flex items-center justify-center pr-18 lg:pr-12">

                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 29 29" id="list" class="h-14">
                                <circle cx="5" cy="5.5" r="2.5" stroke="white"></circle>
                                <path fill="none" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M12.5 6h14"></path>
                                <circle cx="5" cy="14.5" r="2.5" stroke="white"></circle>
                                <path fill="none" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M12.5 15h14"></path>
                                <circle cx="5" cy="23.5" r="2.5" stroke="white"></circle>
                                <path fill="none" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M12.5 24h14"></path>
                            </svg>


                            <span class="self-center text-2xl font-semibold hover:text-blue-200 whitespace-nowrap text-white  pr-2 ml-2">TO DO</span>
                        </a>

                        <ul class="flex flex-wrap justify-center sm:justify-center md:flex-nowrap lg:flex-wrap sm:justify-center lg:pr-16 lg:justify-center     uppercase  mx-auto font-semibold font-heading space-x-4 sm:space-x-6 md:space-x-10 lg:space-x-12 sm:items-center">
                            <li class="text-center xl:mr-14  flex-grow justify-center ">
                                <a class="sm:text-base hover:text-blue-200  " href="create">Add New Task</a>
                            </li>
                            <li class="text-center flex-grow justify-center xl:pr-8">
                                <a class="sm:text-base hover:text-blue-200 xl:ml-10 " href="showAll">Show all Tasks</a>
                            </li>
                        </ul>

  </nav>
</div>
</header>
</body>
</html>