<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>

    <title>ToDo App</title>
    <style>

    </style>
</head>

<body>

    <header>
        <div class=" flex justify-center  w-full h-full  mx-auto">
            <nav class="flex justify-between bg-pink-700 sm:bg-gray-700 md:bg-blue-700 lg:bg-pink-700 text-white w-full items-center">
                <div class="flex flex-wrap sm:flex-col px-3 xl:px-8 py-2  w-full">

                    <div class="lg:flex flex-grow items-center justify-center ">

                        <a href="<?php echo WEB_ROOT; ?>" class="flex items-center justify-center pr-18 lg:pr-12">

                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 29 29" id="list" class="h-14">
  <circle cx="5" cy="5.5" r="2.5" stroke="white"></circle>
  <path fill="none" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M12.5 6h14"></path>
  <circle cx="5" cy="14.5" r="2.5" stroke="white"></circle>
  <path fill="none" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M12.5 15h14"></path>
  <circle cx="5" cy="23.5" r="2.5" stroke="white"></circle>
  <path fill="none" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" d="M12.5 24h14"></path>
</svg>


                            <span class="self-center text-2xl font-semibold hover:text-blue-200 whitespace-nowrap text-white text-center justify-center ml-4">TODO</span>
                        </a>

                        <ul class="flex flex-wrap sm:justify-center md:flex-nowrap lg:flex-wrap  uppercase px-2 mx-auto font-semibold font-heading space-x-4 sm:space-x-6 md:space-x-10 lg:space-x-12 sm:items-center">
                            <li class="text-center lg:mr-14 flex-grow justify-center">
                                <a class="text-base md:text-base sm:text-sm lg:text-lg hover:text-blue-200 py-2 px-4 rounded bg-blue-500 text-white hover:bg-blue-600" href="create">Add New Task</a>
                            </li>
                            <li class="text-center flex-grow justify-center">
                                <a class="text-base md:text-base sm:text-sm lg:text-lg hover:text-blue-200 py-2 px-4 rounded bg-blue-500 text-white hover:bg-blue-600" href="showAll">Show all Tasks</a>
                            </li>
                        </ul>
                        <form class="flex flex-col justify-center items-center ml-auto sm:flex-nowrap md:justify-end lg:justify-center xl:justify-center md:mt-4 lg:ml-4" id="myForm" method="POST" action="showAll">
                            <label data-te-select-label-ref style="color:white;" >Database type</label>
                            <select name="db_type" data-te-select-init onchange="submitForm()">

<option value="json" data-te-select-icon="https://cdn.iconscout.com/icon/free/png-512/free-json-file-1-504451.png?f=avif&w=256" <?php if ($_SESSION['db_type'] == 'json')
                                                                                                                                    echo 'selected'; ?>>JSON</option>
<option value="mysql" data-te-select-icon="https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_mysql_icon_130379.png" <?php if ($_SESSION['db_type'] == 'mysql')
                                                                                                                                echo 'selected'; ?>>MySQL</option>
<option value="mongodb" data-te-select-icon="https://cdn.icon-icons.com/icons2/2415/PNG/512/mongodb_original_logo_icon_146424.png" <?php if ($_SESSION['db_type'] == 'mongodb')
                                                                                                                                        echo 'selected'; ?>>MongoDB</option>
</select>
<script>
function submitForm() {
    document.getElementById('myForm').submit();
}
</script>
                        </form>
                    </div>
                </div>
            </nav>
        </div>

    </header>

</body>

</html>